
import { type Question, LeadershipStyleName } from '../types';

export const questions: Question[] = [
  { id: 1, textKey: 'q1_text', style: LeadershipStyleName.AUTOCRATIC },
  { id: 2, textKey: 'q2_text', style: LeadershipStyleName.DEMOCRATIC },
  { id: 3, textKey: 'q3_text', style: LeadershipStyleName.TRANSFORMATIONAL },
  { id: 4, textKey: 'q4_text', style: LeadershipStyleName.TRANSACTIONAL },
  { id: 5, textKey: 'q5_text', style: LeadershipStyleName.LAISSEZ_FAIRE },
  { id: 6, textKey: 'q6_text', style: LeadershipStyleName.BUREAUCRATIC },
  { id: 7, textKey: 'q7_text', style: LeadershipStyleName.CHARISMATIC },
  { id: 8, textKey: 'q8_text', style: LeadershipStyleName.NATURAL },
  { id: 9, textKey: 'q9_text', style: LeadershipStyleName.TASK_ORIENTED },
  { id: 10, textKey: 'q10_text', style: LeadershipStyleName.RELATIONSHIP_ORIENTED },
  { id: 11, textKey: 'q11_text', style: LeadershipStyleName.VISIONARY },
  { id: 12, textKey: 'q12_text', style: LeadershipStyleName.AUTOCRATIC },
  { id: 13, textKey: 'q13_text', style: LeadershipStyleName.DEMOCRATIC },
  { id: 14, textKey: 'q14_text', style: LeadershipStyleName.TRANSFORMATIONAL },
  { id: 15, textKey: 'q15_text', style: LeadershipStyleName.TRANSACTIONAL },
  { id: 16, textKey: 'q16_text', style: LeadershipStyleName.LAISSEZ_FAIRE },
  { id: 17, textKey: 'q17_text', style: LeadershipStyleName.BUREAUCRATIC },
  { id: 18, textKey: 'q18_text', style: LeadershipStyleName.CHARISMATIC },
  { id: 19, textKey: 'q19_text', style: LeadershipStyleName.NATURAL },
  { id: 20, textKey: 'q20_text', style: LeadershipStyleName.TASK_ORIENTED },
  { id: 21, textKey: 'q21_text', style: LeadershipStyleName.RELATIONSHIP_ORIENTED },
  { id: 22, textKey: 'q22_text', style: LeadershipStyleName.VISIONARY },
  { id: 23, textKey: 'q23_text', style: LeadershipStyleName.AUTOCRATIC },
  { id: 24, textKey: 'q24_text', style: LeadershipStyleName.DEMOCRATIC },
  { id: 25, textKey: 'q25_text', style: LeadershipStyleName.TRANSFORMATIONAL },
  { id: 26, textKey: 'q26_text', style: LeadershipStyleName.TRANSACTIONAL },
  { id: 27, textKey: 'q27_text', style: LeadershipStyleName.LAISSEZ_FAIRE },
  { id: 28, textKey: 'q28_text', style: LeadershipStyleName.BUREAUCRATIC },
  { id: 29, textKey: 'q29_text', style: LeadershipStyleName.CHARISMATIC },
  { id: 30, textKey: 'q30_text', style: LeadershipStyleName.NATURAL },
  { id: 31, textKey: 'q31_text', style: LeadershipStyleName.TASK_ORIENTED },
  { id: 32, textKey: 'q32_text', style: LeadershipStyleName.RELATIONSHIP_ORIENTED },
  { id: 33, textKey: 'q33_text', style: LeadershipStyleName.VISIONARY },
  { id: 34, textKey: 'q34_text', style: LeadershipStyleName.AUTOCRATIC },
  { id: 35, textKey: 'q35_text', style: LeadershipStyleName.DEMOCRATIC },
  { id: 36, textKey: 'q36_text', style: LeadershipStyleName.TRANSFORMATIONAL },
  { id: 37, textKey: 'q37_text', style: LeadershipStyleName.TRANSACTIONAL },
  { id: 38, textKey: 'q38_text', style: LeadershipStyleName.LAISSEZ_FAIRE },
  { id: 39, textKey: 'q39_text', style: LeadershipStyleName.BUREAUCRATIC },
  { id: 40, textKey: 'q40_text', style: LeadershipStyleName.RELATIONSHIP_ORIENTED },
];

export const TOTAL_QUESTIONS = questions.length;
